indykite/indykite-sdk-python

- tests/test_introspect_token.py
> Add introspect token unit test

- setup.py
Specify encoding when calling open() method
> fix: add encoding when open files

- .github/workflows/release-notes.yaml
> ci: use pat token to trigger publish

- .github/workflows/pr.yaml
- Pipfile
- Pipfile.lock
- README.md
- codecov.yaml
- gen_proto.sh
> Add codecov

- .github/workflows/tests.yaml
- jarvis_sdk/README.md
Upload Codecov report on merge into master.
> ci: upload codecov report on merge to master

- .coveragerc
- README.md
- codecov.yaml
- jarvis_sdk/api.py
- jarvis_sdk/cmd/_introspect_token.py
- tests/test_api.py
- tests/test_introspect_token.py
- tests/utils/test_deserialize_digital_twin_with_token_info.py
- tests/utils/test_message_to_value.py
- tests/utils/test_timestamp.py
* Excluded all test code from coverage
* Added tests for api and utils functions
> test: exclude test code from codecov and add api and utils tests

- .coveragerc
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- codecov.yaml
- pytest.ini
Remove Api tests from pytest in Github workflow.
> ci: remove api tests from pytest in gh workflow

- .github/workflows/release.yaml
> ci: remove clickup release step

- .github/workflows/release.yaml
> ci: switch to identity workload provider

- README.md
- jarvis_sdk/cmd/helper.py
- tests/test_change_password.py
- tests/test_delete.py
- tests/test_enrich_token.py
- tests/test_introspect_token.py
- tests/test_patch_properties.py
Issues: 
* https://github.com/indykite/jarvis-backlog/issues/300
* https://github.com/indykite/jarvis-backlog/issues/2618
> Mock gRPC server for unit tests

- README.md
- jarvis_sdk/ingest/__init__.py
- tests/test_stream_records.py
Include return response in `ingest_records()`.
> Return response in ingest_records()

- jarvis_sdk/api.py
- jarvis_sdk/cmdconfig/__init__.py
- jarvis_sdk/cmdconfig/_application_agent_credential.py
- jarvis_sdk/model/application_agent_credential.py
- jarvis_sdk/model/register_application_agent_credential.py
- tests/helpers/data.py
- tests/test_application_agent_credential.py
> Add config credentials 2799

- jarvis_sdk/api.py
- jarvis_sdk/cmdconfig/__init__.py
- jarvis_sdk/cmdconfig/_service_account_credential.py
- jarvis_sdk/model/register_service_account_credential.py
- jarvis_sdk/model/service_account_credential.py
- tests/helpers/data.py
- tests/test_service_account_credential.py
> feat: add service account credential

- .github/workflows/release-notes.yaml
- Pipfile
- Pipfile.lock
- README.md
- indykite_sdk/README.md
- setup.py
changed old repo name in files where it was present
> feat: modif with repo name modification

- .github/workflows/release-notes.yaml
- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- Pipfile
- Pipfile.lock
- indykite_sdk/api.py
- pylintrc
- setup.py
> feat: change python version

- indykite_sdk/api.py
- indykite_sdk/authorization/__init__.py
- indykite_sdk/authorization/helper.py
- indykite_sdk/authorization/is_authorized.py
- indykite_sdk/model/is_authorized.py
- tests/test_import_digital_twins.py
- tests/test_is_authorized.py
add is_authorized method with token
> feat: add authorization with token

- indykite_sdk/README.md
- indykite_sdk/api.py
- indykite_sdk/identity/__init__.py
- indykite_sdk/identity/forgotten_password.py
- tests/helpers/data.py
- tests/test_forgotten_password.py
added forgotten password feature to prepare invitation process
> feat: add forgotten password feature

- indykite_sdk/README.md
- indykite_sdk/api.py
- indykite_sdk/identity/__init__.py
- indykite_sdk/identity/get_digital_twin.py
- indykite_sdk/identity/invitation.py
- indykite_sdk/model/invitation.py
- indykite_sdk/utils/message_to_value.py
- tests/test_get_digital_twin.py
- tests/test_invitation.py
- add invitation creation, check status, resend, cancel
> feat: add invitation features

- indykite_sdk/authorization/__init__.py
- indykite_sdk/config/__init__.py
- indykite_sdk/identity/__init__.py
- indykite_sdk/ingest/__init__.py
replace return by raise in init files
> feat: change init returns

- Pipfile.lock
- indykite_sdk/api.py
- indykite_sdk/utils/hash_methods.py
- fixed vulnerabilities from dependabot and code scanning (when from internal) 
See https://github.com/indykite/indykite-sdk-python/security/dependabot
> fix: fixed vulnerabilies from dependabot

- indykite_sdk/README.md
- indykite_sdk/api.py
- indykite_sdk/identity/__init__.py
- indykite_sdk/identity/consent.py
- indykite_sdk/model/consent.py
- indykite_sdk/utils/message_to_value.py
- tests/test_consent.py
add CreateOAuth2ConsentVerifier feature
> feat: create consent challenge verifier

- indykite_sdk/api.py
- indykite_sdk/config/__init__.py
- indykite_sdk/config/config_node.py
- indykite_sdk/model/authorization_policy_config.py
- indykite_sdk/model/authorization_policy_config_status.py
- indykite_sdk/model/config_node.py
- indykite_sdk/utils/sdk_policy_config.json
- tests/helpers/data.py
- tests/helpers/sdk_policy_config.json
- tests/test_config_node.py
- implement authorization policy config node
> feat: add authz policy config node

- indykite_sdk/api.py
- indykite_sdk/config/__init__.py
- indykite_sdk/config/application.py
- indykite_sdk/config/application_agent.py
- indykite_sdk/config/create_application_with_agent_credentials.py
- indykite_sdk/config/helper.py
- indykite_sdk/model/create_application.py
- indykite_sdk/model/create_application_agent.py
- indykite_sdk/model/key_type.py
- tests/test_create_application_with_agent_credentials.py
- add method to create application, appagent and appagent credentials
> add create app with appagent cred

- indykite_sdk/api.py
- indykite_sdk/authorization/is_authorized.py
- indykite_sdk/authorization/what_authorized.py
- indykite_sdk/authorization/who_authorized.py
- indykite_sdk/config/helper.py
- indykite_sdk/indykite/authorization/v1beta1/authorization_service_pb2.py
- indykite_sdk/indykite/authorization/v1beta1/model_pb2.py
- tests/test_is_authorized.py
- tests/test_what_authorized.py
- tests/test_who_authorized.py
- replace options by input_params in authz
- add tags in authz
> feat: change options and add tags

- Pipfile.lock
- indykite_sdk/api.py
- indykite_sdk/identity/__init__.py
- indykite_sdk/identity/get_digital_twin.py
- tests/helpers/data.py
- tests/test_get_digital_twin.py
add get digital twin by property
> feat: get DT by property

- .gitignore
- indykite_sdk/README.md
- indykite_sdk/ingest/ingest_record.py
- indykite_sdk/model/change_data_type.py
- indykite_sdk/model/ingest_record.py
add info parameter in ingest and stream
> feat: add info in ingest

- indykite_sdk/api.py
- indykite_sdk/config/__init__.py
- indykite_sdk/config/config_node.py
- indykite_sdk/model/config_node.py
- indykite_sdk/model/create_config_node.py
- indykite_sdk/model/knowledge_graph_schema_config.py
- indykite_sdk/model/readid_provider_config.py
- indykite_sdk/model/update_config_node.py
- indykite_sdk/utils/sdk_policy_config.json
- indykite_sdk/utils/sdk_schema.txt
- tests/helpers/data.py
- tests/helpers/sdk_schema.txt
- tests/test_config_node.py
- added readid config node
- added kg schema config node
> feat: add readid and kg schema config nodes

- .coveragerc
- codecov.yaml
- indykite_sdk/api.py
- indykite_sdk/api_helper.py
- indykite_sdk/identity/change_password.py
- indykite_sdk/identity/consent.py
- indykite_sdk/identity/delete.py
- indykite_sdk/identity/enrich_token.py
- indykite_sdk/identity/forgotten_password.py
- indykite_sdk/identity/get_digital_twin.py
- indykite_sdk/identity/import_digital_twins.py
- indykite_sdk/identity/invitation.py
- indykite_sdk/identity/patch_properties.py
- indykite_sdk/identity/register_digital_twins_no_cred.py
- indykite_sdk/identity/token_introspect.py
- indykite_sdk/identity/verification.py
- indykite_sdk/model/change_password.py
- indykite_sdk/model/token_info.py
- tests/test_patch_properties.py
- add explanations in api
- update outdated identity methods
- add docstring in identity methods
> feat: update identity methods

- .coveragerc
- Pipfile.lock
- codecov.yaml
- examples/spaces/Pipfile.lock
- indykite_sdk/api.py
- indykite_sdk/identity/__init__.py
- indykite_sdk/identity/create_custom_login_token.py
- indykite_sdk/model/create_custom_login_token.py
- indykite_sdk/model/digital_twin.py
- tests/test_create_custom_login_token.py
- add custom login token
- update dependencies
> feat: custom login token

- tests/test_is_authorized.py
- tests/test_what_authorized.py
-authz tests have new error messages
> test: update when new error messages

- indykite_sdk/README.md
- indykite_sdk/api.py
- indykite_sdk/authorization/__init__.py
- indykite_sdk/config/__init__.py
- indykite_sdk/identity/__init__.py
- indykite_sdk/ingest/__init__.py
- indykite_sdk/utils/jwt_credentials.py
- tests/test_customer.py
- tests/test_is_authorized.py
- tests/test_what_authorized.py
Closing ENG-1578
remove local argument
> feat: remove local argument

- indykite_sdk/api.py
- indykite_sdk/ingest/__init__.py
- indykite_sdk/ingest/ingest_record.py
- tests/test_ingest.py
ENG-1602
-update ingest methods
> feat: update ingest methods

- examples/spaces/Pipfile
- examples/spaces/Pipfile.lock
- indykite_sdk/api.py
- indykite_sdk/ingest/__init__.py
- indykite_sdk/ingest/ingest_record.py
- indykite_sdk/ingest/stream_records.py
> feat: separate stream from ingest

- examples/spaces/Pipfile
- examples/spaces/Pipfile.lock
> feat: update dependencies

- .github/workflows/release.yaml
- .github/workflows/tests.yaml
- indykite_sdk/api.py
- indykite_sdk/ingest/__init__.py
- indykite_sdk/ingest/ingest_record.py
- tests/test_ingest.py
- tests/test_what_authorized.py
BREAKING CHANGES: Implementing ENG-2457
- update config file
- remove deprecated params in ingest node DT
> feat: clean identity deprecated param

- tests/test_customer.py
> test: update customer tests

- Pipfile
- Pipfile.lock
- indykite_sdk/api.py
- indykite_sdk/indykite/knowledge/objects/v1beta1/ikg_pb2.py
- indykite_sdk/ingest/ingest_record.py
- indykite_sdk/knowledge/identity_knowledge.py
- indykite_sdk/model/identity_knowledge.py
- indykite_sdk/utils/message_to_value.py
- tests/test_ingest.py
- tests/test_knowledge.py
> feat: add metadata to knowledge api properties

- .deepsource.toml
> feat: add deepsource file

- tests/test_service_account.py
> feat: remove outdated authn methods

- Pipfile.lock
- README.md
> feat: add field in app space and consent

- tests/test_create_application_with_agent_credentials.py
- tests/test_customer.py
- tests/test_is_authorized.py
- tests/test_service_account.py
- tests/test_service_account_credential.py
- tests/test_what_authorized.py
- tests/test_who_authorized.py
implement ENG-4427
- some refactorization
> feat: add entitymatching and delete tags

- indykite_sdk/config/__init__.py
- indykite_sdk/config/config_node.py
- indykite_sdk/entitymatching/run_entity_matching_pipeline.py
- indykite_sdk/indykite/entitymatching/v1beta1/entity_matching_api_pb2.py
- indykite_sdk/indykite/entitymatching/v1beta1/entity_matching_api_pb2_grpc.py
- indykite_sdk/indykite/entitymatching/v1beta1/model_pb2.py
- indykite_sdk/model/entity_matching_pipeline_config.py
- indykite_sdk/usage/entitymatching.py
- indykite_sdk/usage/ingest.py
- tests/test_config_node.py
implement ENG-5055
- update entitymatching
- fix package
> feat: update EM and fix package

- .github/workflows/release.yaml
- Pipfile.lock
- README.md
- tests/test_config_node.py
> feat: update eventsink config node

- .github/workflows/release-notes.yaml
- ci: release Slack notifications debugging
> ci: release slack notification
